### ISSUE TITLE
Show the quantity and amount of each Mode of Payment

### ISSUE THREAD

**Issue by agritheory** [agritheory/check_run#110]
And for checks, show the split based on the value/default in Check Run Settings

This would be a Vue component ~2/2.5 lines high that floats on the bottom of the page showing the various modes of payment selected and their totals.

(4) ACH/EFT: $1,500.00 | (15/11) Check: $3615.00 | (1) Cash: $100.0

**Comment by fproldan** [comment]
@agritheory I need further explanation on "And for checks, show the split based on the value/default in Check Run Settings". Which field in Check Run Settings I should take?

**Comment by agritheory** [comment]
@fproldan "Number of invoices per voucher" - top right of this screenshot

![](https://agritheory.com/documentation/check_run/assets/SettingsDefaultScreen.png)
