### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by HKuz** [agritheory/check_run#13]
To keep track of documentation topics to add and where they stand:

## Using Check Run

- [x] Installation guide (see `installationguide.md`, README links there, too)
- [x] How it works / what it does (see `index.md`)
- [x] Key navigation
- [x] Configuring Mode of Payment for Employees and Suppliers (see `configuration.md`)
- [x] Example data (see `exampledata.md`)
- [x] Render PDF sequence
- [x] ACH generation
- [x] Example voucher check print format
- [x] Positive Pay (see `positivepay.md`)
- [x] Check Run Settings
- [x] Permissions:
    - [x] first user on Record feature,
    - [x] only one draft per account/ payable combination allowed,
    - [x] recommended Roles and permissions

## Settings

- [x] Include Journal Entries
- [x] Include Expense Claims
- [x] Check overdue items automatically
- [x] Allow cancellation, cascade cancellation to payment entries?
- [x] ACH file options like file extension, more options

## Installation Guide

- [ ] Production environment steps
- [ ] ~~Confirm app works with ERPNext V14 (it doesn't, new issue created to address this)~~

**Comment by agritheory** [comment]
@HKuz I think we can close this, there are no special production environment steps
