### ISSUE TITLE
Feature: Use right-docked flyin for preview of attachments 

### ISSUE THREAD

**Issue by agritheory** [agritheory/check_run#136]
This feature should be accessible in three places:
In every file attachment: 
![image](https://github.com/agritheory/check_run/assets/18033666/98256f0e-0f56-43ff-ba13-183c1062f4d5)

![image](https://github.com/agritheory/check_run/assets/18033666/b8509c93-3019-4507-94e4-4e8395c25f7b)

In the Check Run selection pane:
![image](https://github.com/agritheory/check_run/assets/18033666/2b4cf09b-f295-42ce-9893-0cc4f4052761)

And from a new report "Payables Attachments" - based on the visible columns in the Purchase Invoice Report View, plus a column for attachments. In this view the flyin can be visible all the time.

**Comment by agritheory** [comment]
@fproldan Work in progress is available on the branch `preview`

**Comment by fproldan** [comment]
@agritheory In the case of Check Run, how about the option of using a dropdown when there is more than one attachment? (with a more polished design)

[screencast-127.0.0.1_8002-2023.08.18-11_52_00.webm](https://github.com/agritheory/check_run/assets/4945122/cd82173e-85b8-4740-b0ba-4d559cce3e16)
