### ISSUE TITLE
Port to V15

### ISSUE THREAD

**Issue by batonac** [agritheory/check_run#158]
I've tested on `version-15-beta` versions of Frappe, ERPNext, and HRMS. The following issues will need to be resolved:

- [ ] Frappe no longer requires `PyPDF2`. Either port the code to `pypdf` or explicitly require `pypdf2`.
- [x] Update to Vue 3.
If/when you're ready to open a v15 branch, I'd be glad to work on these.

**Comment by agritheory** [comment]
Let's add PyPDF as a dependency. We'll will want to update to Vue 3 as well, which is covered in [the migration guide](https://github.com/frappe/frappe/wiki/Migrating-to-nightly-version-%28future-v15%29#migrate-to-vue3) but not in any detail

**Comment by agritheory** [comment]
Looks like they are using `pypdf` but not `pypdf2` https://github.com/frappe/frappe/blob/develop/pyproject.toml#L21C6-L21C11

**Comment by agritheory** [comment]
https://frappeframework.com/docs/user/en/basics/doctypes/controllers#type-annotations

**Comment by agritheory** [comment]
`version-15` branch is now live
