### ISSUE TITLE
Quick Print Check Feature from Payment Entry

### ISSUE THREAD

**Issue by Mboo42** [agritheory/check_run#170]
Request- We would like to see an option to quickly print a check from the Payment Entry screen. 

In order to ensure the print check feature is controlled, we believe that the payment entry form should require a linked voucher (purchase invoice) to be present before allowing the print check action to be enabled.

**Comment by agritheory** [comment]
@Mboo42 This seems like a straightforward feature to implement. What's missing at present is pulling the default mode of payment from the supplier and requiring references when the payment type != 'Internal Transfer'
