### ISSUE TITLE
Large count invoice freeze

### ISSUE THREAD

**Issue by robproject** [agritheory/check_run#175]
When a large number of invoices is to be paid in a single check run (100+), the system hangs

**Comment by robproject** [comment]
Appears to be issue with development environment - large http payloads are not getting to the python application layer, the browser console is not displaying an error, only the network tab shows the request is pending.

**Comment by agritheory** [comment]
How did you resolve the issue?

**Comment by robproject** [comment]
The issue was intermittent and related only to my development environment - here is a summary. In each case, having the browser's developer console open caused delays and my current setup is only reliable for larger amounts (60~100) of payment entries when developer console is closed. I didn't realize the first setup was using an unreleased Debian version until investigating this.

1. Host: MacOS 14.1 arm64
Hypervisor/Engine: UTM (QEMU)
VM/Container: Debian 13
IDE: VSCodium/Remote SSH
Note: unresponsive when working with more than ~30 entries, regardless of developer console

 2. Host: MacOS 14.1 arm64
 Hypervisor/Engine: UTM (QEMU) 
VM/Container: Debian 12 
IDE: VSCodium/Remote SSH 
Note: wkhtmltopdf issues

 3. Host: Debian 12 amd64
 Hypervisor/Engine: Docker
 VM/Container: Debian 11 (github.com/frappe/frappe_docker development setup)
 IDE: VSCode/Remote devcontainer + remote ssh via tailscale
 Note: No compatibility issues; current setup
