### ISSUE TITLE
Build command should build both local and Frappe-bundled assets

### ISSUE THREAD

**Issue by agritheory** [agritheory/check_run#188]

**Comment by fproldan** [comment]
@agritheory 

I've tried adding `&& node ../frappe/esbuild` to the Vite build without success, it generates the bundles but throws  `postcss2` errors in the terminal.

I also created a new bench from scratch and installed the check run app, in the process a build is run, so the bundles and the `check_run.js`, and `style.css` are generated when you add the app to a bench.
