### ISSUE TITLE
Ending Check Run Number should be recomputed after validate and after `_process_check_run`

### ISSUE THREAD

**Issue by agritheory** [agritheory/check_run#196]
The validation that removes paid invoices/ EC/ JE from the list is run in get_entries or when the user saves the document, meaning that the total number of checks should be known at either point.

To reproduce:
- Start a Check Run, mark an invoice to be paid, save it
- Manually pay that invoice
- Save the Check Run to ensure that that invoice is removed and that the ending check number is updated correctly

**Comment by viralkansodiya** [comment]
@agritheory 
I have tested this case multiple times, Please watch the below video

Solution
https://www.youtube.com/watch?v=I1Kq9CKP2wk

we can replace a last msg with below

<img width="717" alt="msg" src="https://github.com/agritheory/check_run/assets/141210323/ffd7e6c2-7960-4646-8d22-acc0940e1e7e">

Please give your feedback

**Comment by agritheory** [comment]
@viralkansodiya I think we can close this ticket as resolved. Thanks for the detective work.
