### ISSUE TITLE
Improve Payment Entry Error messages for better compatibility with Check Run

### ISSUE THREAD

**Issue by agritheory** [agritheory/check_run#203]
Override validation error message in Payment Entry to show what document (PE), reference name and `bill_no` if it exists in `validate_allocated_amount` and `validate_allocated_amount_with_latest_data`

```python
frappe.throw(
	f"{self.party_name} Row {d.idx} / {d.reference_name}: Allocated Amount of {d.allocated_amount} cannot be greater than outstanding amount of {d.outstanding_amount}."
)
```

**Comment by agritheory** [comment]
@basawaraj-fosserp @viralkansodiya Can you take a look at this one?

**Comment by viralkansodiya** [comment]
@agritheory  will check this and update you

**Comment by viralkansodiya** [comment]
@agritheory 
can we wright this msg as below, I think this looks better 

f"<b>Row {d.idx}</b> {self.party_name} / {d.reference_name}: Allocated Amount of {d.allocated_amount} cannot be greater than outstanding amount of {d.outstanding_amount}."

<img width="660" alt="msg" src="https://github.com/agritheory/check_run/assets/141210323/540f583e-8ab6-45b2-a895-495d40718523">
