### ISSUE TITLE
Add option to disallow Purchase Returns

### ISSUE THREAD

**Issue by agritheory** [agritheory/check_run#213]
As a matter of company policy, it may be desirable to require the AP clerk to process returns or credit notes against an invoice rather than netting against a payment (without reducing the AP of a specific invoice). 

Select field in Check Run Settings with the options "Disallow Returns and Credit Notes" and "Allow Returns and Credit Notes"

**Comment by basawaraj-fosserp** [comment]
@agritheory as of latest v14 of ERPNext, I can create a stand-alone debit note. Stand-alone debit note is not against a specific purchase invoice. Such stand-alone debit notes should either be allowed or not based on the select field in 'Check Run Settings'. This is my understanding of this feature request. Are we on the same page here?

**Comment by agritheory** [comment]
@basawaraj-fosserp That's correct. They are currently allowed by default but I think it makes sense to disallow it if your companies' policy is to require matching. Karmic accounting.
