### ISSUE TITLE
bug: Error during check run process

### ISSUE THREAD

**Issue by viralkansodiya** [agritheory/check_run#236]
https://github.com/agritheory/check_run/assets/141210323/30abe85d-2455-474d-aa3a-b5bccc02ae53

@agritheory 
This bug I have found in `tax_payable` branch 

![check run error](https://github.com/agritheory/check_run/assets/141210323/b9efe38d-5957-4b2f-8976-008884f7b847)

**Comment by agritheory** [comment]
I think the solution for this should be to make the the Bank Account and Pay To fields read only.

**Comment by fitch20** [comment]
@viralkansodiya can you help with set up , please 
I will pay 
Here is my telegram username: @Fitch24
