### ISSUE TITLE
file_preview.js not working without reload for different doctype

### ISSUE THREAD

**Issue by MinHyeong-Lee** [agritheory/check_run#255]
Hello. 
I installed **check run** app on my frappe.
This app is very comfortable. Thank you. 
There is a code that I modified while using it. It would be great if you could check it.

https://github.com/agritheory/check_run/blob/46a084a3cf862e06bbd3a0b9c81ecd5e6a683d07/check_run/public/js/custom/file_preview.js#L52-L75

File preview is really cool.
But, there are two problems with the **File preview**. 
1. It does not work if the file extension is uppercase PDF. 
I modified like this code.
```javascript
//Before
file_name.endsWith('.pdf')
//After
file_name.toLowerCase().endsWith('.pdf')
```
2. When I checked **Frappe** source code, I found that independent **<div>** element were continuously created for each opened doctype.  So, when the page was moved to a different doctype, **<div>** with duplicated id ("#pdf-preview-wrapper") were continuously added and the file preview did not work.

I modified like this code.
```javascript
// Line 65
// Before
frappe.ui.addFilePreviewWrapper();
// After
frappe.ui.addFilePreviewWrapper(cur_frm);

// Line 69 - 75
//Before
frappe.ui.addFilePreviewWrapper = () => { 
 	if ($('#pdf-preview-wrapper').length == 0) { 
 		$('.page-body .page-wrapper').append(`<div id="pdf-preview-wrapper"> 
 		<button class="btn btn-secondary btn-default btn-sm" id='close-pdf-button'>Close PDF Preview</button> 
 		</div>`) 
 	} 
 } 
//After
frappe.ui.addFilePreviewWrapper = frm => {
	$('#pdf-preview-wrapper').remove()
	let targetDiv = document.querySelector(`[id='page-${frm.doctype}']`)
	if (targetDiv) {
		let page_body = targetDiv.querySelector('.page-body')
		if (page_body) {
			let page_wrapper = page_body.querySelector('.page-wrapper')

			if (page_wrapper) {
				$(page_wrapper).append(`<div id="pdf-preview-wrapper">
			<button class="btn btn-secondary btn-default btn-sm" id='close-pdf-button'>Close PDF Preview</button>
			</div>`)
			}
		}
	}
}
```

Thank you for reading. 
If you have any intention of modifying it, it would be a good idea to reflect it in the repository.

**Comment by agritheory** [comment]
Thanks @MinHyeong-Lee. We can incorporate these bug fixes into a pull request.
