### ISSUE TITLE
Feature Request: Option to differentiate between Immediate Destination and Immediate Origin in NACHA file output

### ISSUE THREAD

**Issue by trustedcomputer** [agritheory/check_run#73]
JPMorgan Chase Bank requires different values for Immediate Destination and Immediate Origin fields in the File Header section of the NACHA file output. They require a value of 0000000000 for Immediate Origin and the Routing Number for the Immediate Destination.

Currently, both values are set in apps/check_run/check_run/check_run/doctype/check_run/check_run.py (lines 593 and 594) to the same variable **company_bank_aba_number** fetched from the branch_code field of the Bank Account document (line 542):

```
company_bank_aba_number = frappe.db.get_value('Bank Account', doc.bank_account, 'branch_code')
....
immediate_destination=company_bank_aba_number if not settings.omit_destination else "",
immediate_origin=company_bank_aba_number,
```

It would be great to accommodate this requirement somehow.

**Comment by trustedcomputer** [comment]
Reference: 
![File-Header](https://user-images.githubusercontent.com/75872475/223566193-2d630713-f840-44ba-8625-b2f505eaeae9.png)

**Comment by agritheory** [comment]
@put3r-r00t3r Hi Ben, I think it would make the most sense to refactor the 'Omit Destination' option in Check Run settings to accept the sort of value you are looking for, rather than being a checkbox. 

Is this something you'd be able to contribute or are you looking for a hand?

**Comment by trustedcomputer** [comment]
@agritheory I could certainly try! It would be my first PR, so I'd need to learn that process. 

I'm actually curious about the "Omit Destination" checkbox. In theory, according to the [published specifications](https://achdevguide.nacha.org/ach-file-details), the Immediate Destination field is always "The nine-digit routing number of the institution receiving the ACH file for processing, preceded by a blank. Typically, this is your bank’s routing and transit number." 

It's the Immediate Origin that may be variable: "The nine-digit routing transit number of the institution sending (originating) the ACH file, preceded by a blank. (Often your ODFI will have you insert your company ID in this field.)"

So yes, if the "Omit Destination" field is not needed, then we could remove that and put in its place a field to accept a custom "Immediate Origin".

If that idea works for you, then I'll try my hand at the JSON and python and figuring out the PR process.

**Comment by agritheory** [comment]
@put3r-r00t3r Where this PR would require a patch to modify a fieldtype in deployed installations, I don't think it's a good candidate for a first PR; I'd be happy to pick this one up. #74 Is better candidate for a first contribution.
