### ISSUE TITLE
Feature Request: Ability to change Effective Entry Date

### ISSUE THREAD

**Issue by trustedcomputer** [agritheory/check_run#80]
I get this error from JPMorgan Chase when I upload my ACH File:

Batch 1: We can't accept this file because it includes an effective entry date that's in the past or falls on a non-business day. Dates must allow at least 2 days for employee payments, 1 day for vendor payments or 1 day for ACH collections to be processed.

This is because the effective_entry_date and the file_creation_date are both using the getdate() function, and end up the same date. I propose using the check run doc's posting_date for the effective entry date. For people that don't need to customize, it will still be the same as before. For people that do, they can use the "Posting Date" field to set the Effective Entry Date as needed.

I've tested this in my fork and it seems to be working correctly for me. I can create a PR.

**Comment by trustedcomputer** [comment]
Here's the code I would change:
`effective_entry_date=doc.posting_date,`

**Comment by agritheory** [comment]
@put3r-r00t3r Sounds good to me. Please add some notes in the ACH docs in your pull request

**Comment by trustedcomputer** [comment]
https://github.com/agritheory/check_run/pull/89

**Comment by agritheory** [comment]
Resolved with #89
