### ISSUE TITLE
Feature Request: Individual Identification Number

### ISSUE THREAD

**Issue by trustedcomputer** [agritheory/check_run#81]
I get this error from JPMorgan Chase when I upload my ACH File:

Batch 1, Transaction XXXXXXXXX: Please tell us an individual identification number using only letters and numbers because special characters aren't accepted. Remember that identification numbers should never be social security numbers. Please see the Chase file specs for more information. (Error code: 57090)

This is because currently, individual_id_number='' in check_run.py. I propose setting this to pe.party, but stripping non-alphanumeric characters and making it all upper case. I've tested some code to do this in my fork and it's working for me. I can create a PR.

This might be kind of an edge case, though. I'm not sure how many other banks need this field set in the NACHA file. According to the NACHA [dev guide](https://achdevguide.nacha.org/ach-file-details) it's an optional field. Unfortunately, Chase has decided to make it mandatory for them. Let me know if you think this would be useful to have or not.

**Comment by trustedcomputer** [comment]
Here's the code I would change:
`individual_id_number=''.join(c for c in pe.party if c.isalnum()).upper(),`

**Comment by agritheory** [comment]
@put3r-r00t3r This is fine start but also needs to respect the individual number length
I would also suggest that it be `party_name` and not `party` for cases where you're using a naming series to identify an employee or supplier.

**Comment by trustedcomputer** [comment]
@agritheory Thanks- regarding party_name/party, actually that's why I initially thought party would be better than party_name. Because if a naming series is being used, it would be more of what that ACH field was designed to hold while in the next line, `individual_name=pe.party_name`. My read on the docs was that the "Individual Identification Number" was supposed to be something of a unique identifier to the originator, whereas "Individual Name" was supposed to be more of a description. But maybe I'm not interpreting that correctly?

**Comment by agritheory** [comment]
Yeah, that's a fine argument for it as well; it probably depends on how human-readable it needs to be. We could make it an option in Check Run Settings.

**Comment by trustedcomputer** [comment]
First of all, yes, this is still me. I did a name change to be a little more professional and use my business name.

Here is the [pull request](https://github.com/agritheory/check_run/pull/94) for this. I added the option of which field to use for this in check run settings. I've tested this on my own install and it seems to be working correctly. Let me know if you see any changes needed.

**Comment by trustedcomputer** [comment]
I closed the old PR because it was in conflict with new commits. Here is the new [pull request](https://github.com/agritheory/check_run/pull/102).
